name: Deploy to VPS

on:
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v212

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAME_HOST }}
          username: ${{ secrets.USER_HOST }}
          key: ${{ secrets.KEY_SSH }}
          script: |
              cd /var/www/Zooland
              git pull
              docker-compose down
              docker-compose up --build -d
              sleep 10
              docker ps -a # to list all running containers
