name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAME_HOST }}
          username: ${{ secrets.USER_HOST }}
          key: ${{ secrets.KEY_SSH }}
          script: |
            echo "Host *" >> ~/.ssh/config
            echo " StrictHostKeyChecking no" >> ~/.ssh/config
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            cd /var/www/Zooland
            git remote set-url origin git@github.com:username/repo.git
            git pull
            cd server
            npm install
            npm run build # this runs "tsc"
            docker-compose down
            docker network prune -f
            docker-compose up --build -d
            sleep 10
            docker ps -a # to list all running containers
