name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAME_HOST }}
          username: ${{ secrets.USER_HOST }}
          key: ${{ secrets.KEY_SSH }}
          script: |
            cd /var/www/Zooland
            git pull
            cd server
            npm install
            npm run build # this runs "tsc"
            nano src/server.ts
            docker-compose down
            docker-compose up --build -d
            sleep 10
            docker ps -a # to list all running containers
